language: python

os:
  - linux
  - osx

matrix:
  include:
  - python: 3.6.10

before_install:
  # Here we just install Miniconda, which you shouldn't have to change.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install -e environment.yml

script:
  - git clone git@github.com:rstatistics/PathogenTrack.git

branches:
  only:
    - master

notifications:
  email: false
