name: PathogenTrack
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO docker: Add required software dependencies here
  - samtools=1.9
  - star=2.7.5a
  - python=3.6.10
  - biopython=1.78
  - umi_tools=1.0.1
  - kraken2

